### ISSUE TITLE
Clarify README that this does not (yet?) run `buf generate`, and is thus complementary not replacing the protobuf-gradle-plugin

### ISSUE THREAD

**Issue by vorburger** [andrewparmet/buf-gradle-plugin#24]
It took me second to realize that this does not (yet?) run `buf generate`, and is thus complementary to but not replacing the protobuf-gradle-plugin. Reading _Integration for Buf with the protobuf-gradle-plugin._ made me assume otherwise initially. Perhaps this could be clarified on the README? I'll propose a PR.

**Comment by andrewparmet** [comment]
It was not the original intent of this plugin to call `protoc` (or equivalent) via `buf generate` as Buf did not offer that functionality at the time and the protobuf-gradle-plugin handles that work. It is meant to be a linter/checker on top of the protobuf-gradle-plugin which allows you to continue to leverage its functionality (such as declaring `protobuf` dependencies, additional plugins, etc). 

A full Buf integration would start to imply ownership of a much larger feature domain - one that the protobuf-gradle-plugin handles well already. This is a symptom of Buf expanding to try to be a one-size-fits-all tool while the protobuf-gradle-plugin already fills many of those needs for JVM projects.

I will clarify the README. Thanks for the suggestion!

**Comment by andrewparmet** [comment]
Clarified in 4129212.

**Comment by andrewparmet** [comment]
If one day it becomes clear that `buf generate` is a stronger tool than the `protobuf-gradle-plugin` (or supports features that Google won't support in the `protobuf-gradle-plugin` and there's an overwhelming reason to support them here) I'd be open to supporting `buf generate` in this plugin. That's a big lift though!

**Comment by jcogilvie** [comment]
I would like to +1 the idea of supporting `buf generate` in some capacity because of buf's [managed mode](https://docs.buf.build/generate/managed-mode/) that removes consumer-side concerns from the proto definitions.

**Comment by andrewparmet** [comment]
That's a nice feature I haven't seen before and compelling enough to consider including.

Thinking about it holistically `buf generate` would seem slightly out of scope for this plugin as it stands though - [like I suggested on #26](https://github.com/andrewparmet/buf-gradle-plugin/issues/26#issuecomment-919540370) would it make sense to just have a simple Exec task to invoke Buf and generate that code as a dependency of the `compileJava` task?

That task could be relocated to this plugin if it doesn't clutter up the config too much, but I think it probably should stand separately. Morphing this plugin into a general-purpose Buf integration would require overhauling the existing functionality to remove the implicit dependency on the `protobuf-gradle-plugin`, and I'd also have to figure out how to handle conflicts that arise when both `buf generate` and the `protobuf-gradle-plugin` are enabled. I think it would be easy to misconfigure this plugin and end up in a confusing state with multiple copies of generated code - some generated with the embedded file options, some with other options from `buf.gen.yaml`, etc.

On top of that issue Buf is changing rapidly and supporting its pace is already a bit of a chore for the current behavior. Given that Buf seems to be slowly attempting to handle all protobuf reponsibility, maybe one day a simple Exec task will be all we need and this plugin can be sunset.

**Comment by jcogilvie** [comment]
I think buf is going to continue to try to supplant the rest of the protobuf toolchain.  It's at a place now where it's using protoc to build things, so there's not a whole lot for `protobuf-gradle-plugin` to do.  With that in mind I wouldn't worry too much about people using both.  

At the very least this plugin provides a nice containerized `buf` to execute against so I don't need to have `buf` locally.  I could see the plugin one day just wrapping the docker container with some default opinions about source sets.  

As an aside, I think the use case you're currently trying to cover here might be very close to ["buf as protoc plugin"](https://docs.buf.build/lint/protoc-plugin/).

**Comment by andrewparmet** [comment]
Yeah, it would be ok if this eventually became simply an interface between Gradle and calling Buf.

I originally wanted to use Buf as a protoc plugin but I had trouble dynamically downloading it for the `protobuf-gradle-plugin`. Since I was going to have to deal with Docker anyways for building an image, I decided to be consistent and use it for linting and breakage checking as well.

**Comment by andrewparmet** [comment]
`buf generate` is now supported in [0.4.1](https://github.com/andrewparmet/buf-gradle-plugin/releases/tag/0.4.1). Give it a try!
