### ISSUE TITLE
Accept buf.work.yaml files

### ISSUE THREAD

**Issue by jcogilvie** [andrewparmet/buf-gradle-plugin#26]
Buf accepts multiple working directories via `buf.work.yaml`.  It would be very nice if this plugin could support this pattern.  

It's useful in conjunction with something like `protodep` which creates a directory of dependencies which must also be included alongside the project's `buf.yaml`.

**Comment by andrewparmet** [comment]
Can you clarify your use case? What is the relationship between `buf`, `protodep`, and the `protobuf-gradle-plugin` in your workflow?

This plugin is designed to work with definitions that the `protobuf-gradle-plugin` will be using as its input for generating Java/Kotlin/etc. files. It works with [dependencies declared following the standard Gradle dependency management style](https://github.com/google/protobuf-gradle-plugin#protos-in-dependencies).

Could you point the `protobuf-gradle-plugin` at the output of `protodep` (which you'd have to be doing already if you're generating code with it)? If you're not generating files using the `protobuf-gradle-plugin` this plugin might not be the right tool for your use case.

**Comment by jcogilvie** [comment]
The really simple use case is outlined in the doc for [`buf.work.yaml`](https://docs.buf.build/configuration/v1/buf-work-yaml/).  It's for when you have multiple directories of proto files (and multiple `buf.yaml`s) to include in one build.

My specific use case is that I have a directory of proto files that are pulled from remote sources (via protodep, but I suppose that isn't important) in addition to the directory of proto files native to my project.  They have separate `buf.yaml` files, so I can technically work around this by creating two gradle modules, one pointed at each `buf.yaml`.  But really I think the plugin should optionally accept either a `buf.work.yaml`, or one-or-more `buf.yaml` files.  And the working directory for the buf docker image should be set where the `buf.work.yaml` is located to ensure relative paths are resolved correctly.

**Comment by andrewparmet** [comment]
The checks that this plugin implements are meant to work against first-party protobuf rather than third-party protobuf. The only reason I expect you'd want to check against third-party protobuf is when you use their definitions in your own, in which case you'd have to declare the dependencies for the `protobuf-gradle-plugin` as in the link I included above - and then this plugin would see those definitions for its checks.

Are you just looking to invoke Buf against vendored code to detect breaking changes? (I assume you wouldn't lint that code since you can't change it.) That's not a usage I'd encourage (or want to be responsible for) via Gradle - I'd just invoke `buf` as a separate step in CI/CD tooling, or as a Gradle [Exec task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html).

As you mention, when you eventually use those directories as source directories, this plugin will pick up the sources automatically when you declare them to the `protobuf-gradle-plugin`.

**Comment by andrewparmet** [comment]
Related to this: https://github.com/bufbuild/buf/issues/550

Initially this would allow me to stop copying all protobuf into the ephemeral `workspace` directory but would also be a step in the direction of allowing user-supplied `buf.work.yaml` files.

**Comment by andrewparmet** [comment]
I've made some progress on this: https://github.com/andrewparmet/buf-gradle-plugin/commit/288ac768e2838829c516ffb996d7d2500b6ad5d0.

What I'm envisioning now is to rewrite the integration not to copy proto files and instead create a workspace that points back to `src/main/proto`, `build/extracted-include-proto` (protobuf-gradle-plugin dependencies), and `build/extracted-proto` (`protobuf` configuration dependencies - code from other artifacts that the protobuf-gradle-plugin will be generating).

To support a user-supplied `buf.work.yaml` I think I'd have to change the behavior in a way that's incompatible with the protobuf-gradle-plugin. I can easily look for a `buf.work.yaml` in the project directory and tell `buf` to run from there and basically act as a simple wrapper around Docker (or the binary if one day I can resolve that artifact).

This would allow you to call `bufLint`, `bufBuild`, and `bufBreaking` Gradle tasks on vendored protobuf however you choose to vendor it. Those tasks would still be registered as task dependencies of `check` (`bufLint`, `bufBreaking`) and as a publication (`bufBuild`).

What would not be supported is _fusing_ the provided `buf.work.yaml` with the "virtual" `buf.work.yaml` that would be generated for the protobuf-gradle-plugin integration. I think it's probably opening Pandora's box to start parsing that YAML and merging the directories list. Attempting to do that feels like an anti-pattern; if you're going to use the protobuf-gradle-plugin then you should use its dependency management which will work out of the box with the "virtual" `buf.work.yaml`.

On the other hand, if you're going to vendor your own dependencies, you're going to be in the weeds creating a `buf.work.yaml` already. If you want to consider the protobuf-gradle-plugin's directories then you can include those yourself. Maybe one day we'd have `bufGenerate` which would enable code generation without the protobuf-gradle-plugin at all. If no `buf.work.yaml` is provided, then the plugin will simply use `src/main/proto`, etc., as its input the same way the protobuf-gradle-plugin does.

Does that sound like it would work for you?

**Comment by jcogilvie** [comment]
Yes, I absolutely believe I could make that work.  For my use case I'm not worried about the protobuf plugin.  I'm trying to use buf instead due to the support for consumer-side language-specific pragma features (i.e. managed mode).

**Comment by andrewparmet** [comment]
Workspace support has been release in [0.4.0](https://github.com/andrewparmet/buf-gradle-plugin/releases/tag/0.4.0). Try it out and let me know if works or you have any issues!
