### ISSUE TITLE
Add task which will run `buf format`

### ISSUE THREAD

**Issue by marcindabrowski** [andrewparmet/buf-gradle-plugin#65]
It would be nice to have `bufFormat` which can reformat proto files with [buf format](https://docs.buf.build/format/usage).

Actually it would be great if we have `bufCheck` task which could do a `buf lint` and `buf format --exit-code`

**Comment by andrewparmet** [comment]
Good suggestion. This should be straightforward to implement. Feel free to contribute a PR or I can hopefully get to this at some point soon.

**Comment by marcindabrowski** [comment]
I have never implemented the gradle plugin, but will try to find some time, but not sure when.
In case I start I will notice you here.

**Comment by marcindabrowski** [comment]
I've started doing it.

**Comment by aparmet-toast** [comment]
I'm leaning towards opt-out. I'd like to allow users the option to use this plugin solely for breakage checks.

Here's a general outline of the approach:
- Add an option to BufExtension called `enforceFormat` that is `true` by default
- Create two tasks:
    - `bufReformat` reformats code using `buf format -w`.
    - `bufFormat` runs `buf format --exit-code`. It's enabled if the `enforceFormat` option is true. It's run as part of verification (`check` depends on it).

The complication I foresee about is how `buf format` acts on a workspace. For cases where the user is using the `protobuf-gradle-plugin`, we should only format and check the code in the protobuf source sets.

**Comment by andrewparmet** [comment]
I'm leaning towards opt-out. I'd like to allow users the option to use this plugin solely for breakage checks.

Here's a general outline of the approach:

    Add an option to `BufExtension` called `enforceFormat` that is `true` by default
    Create two tasks:
        `bufReformat` reformats code using `buf format -w`.
        `bufFormat `runs `buf format --exit-code`. It's enabled if the enforceFormat option is true. It's run as part of verification (check depends on it).

The complication I foresee about is how buf format acts on a workspace. For cases where the user is using the `protobuf-gradle-plugin`, we should only format and check the code in the protobuf source sets.

**Comment by marcindabrowski** [comment]
I was thinking about two task: `bufFormatCheck` and `bufFormatApply` both in `verification` group like spotless tasks are.
The first one will run `format -d --exit-code` and the second one `format -w`.

I'm not sure how `format` works on workspaces. In the documentation there is only this info `The buf format command has no configuration options.` which suggests that he is ignoring all config used for linting.

Actually I didn't start yet, just planned it for todays evening, so maybe it will be better if you can do it.

**Comment by andrewparmet** [comment]
I like the Spotless conventions for tasks names, but in this case they clash with the convention I picked, which is that I mirror the `buf <foo>` wherever possible... I'll think on it.

**Comment by marcindabrowski** [comment]
I need this feature, so please let me know if I can work on it, or if you will do that.
And give me advice on how you want it to be done.

**Comment by andrewparmet** [comment]
Released in 0.6.0.

**Comment by marcindabrowski** [comment]
Good job. Thanks a lot.
