### ISSUE TITLE
Support generating modules from BSR or git

### ISSUE THREAD

**Issue by adrianNEMO** [andrewparmet/buf-gradle-plugin#74]
It would be super useful to be able to generate external modules. For example I am currently using custom exec Gradle tasks to run a command like `buf generate buf.build/grpc/grpc --path grpc/health/v1`. Which does not use the buf binary configured by this plugin and is a bit cumbersome to add multiple modules.

**Comment by andrewparmet** [comment]
I haven't looked into this deeply yet, but for the time being you can access the `buf` binary downloaded by this plugin like so:

```kotlin
configurations.getByName(BUF_BINARY_CONFIGURATION_NAME).singleFile
```

And then you can run a Gradle [Exec task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html) pointing to the binary. Feel free to share what you come up with and I can look at incorporating it into the plugin.

Is it possible to configure these commands via a `yaml` file that `buf generate` picks up automatically? Or does this have to be a separate command? I'd like to avoid building a config DSL if possible.

**Comment by adrianNEMO** [comment]
Thanks for the quick reply. To my knowledge, it is sadly not possible to configure generating external modules in any buf files.
My setup to generate them is currently like this:
```
tasks.named("bufGenerate").configure {
    dependsOn("bufClean")
    finalizedBy("bufGenerateHealthProbe")
}

tasks.register<Exec>("bufGenerateRendertron") {
    executable = configurations.getByName(BUF_BINARY_CONFIGURATION_NAME).singleFile.absolutePath
    args("generate", "buf.build/grpc/grpc", "--path", "grpc/health/v1", "--output", "$buildDir/$BUF_GENERATED_DIR")
}
```
It would also be helpful to put all buf commands in a group so they are not all in the other group in Gradle.

**Comment by andrewparmet** [comment]
Are you using a Buf workspace? Would it work to include the health probe service as a dependency? https://docs.buf.build/configuration/v1/buf-yaml#deps

I still see a potential use case for one-off generation, but I wonder if it's correct to encourage using proper dependencies since they'll have to coexist with generated code from one's own defined protobuf anyways. The use case for defining protos and then _not_ generating code while also generating third-party dependencies wouldn't be supported, but is that a real use case?

**Comment by remoun** [comment]
I'm running into a similar scenario, where I want to generate code for my buf dependencies. One way to do this is `buf generate --include-imports`; can we add support for that flag in the `buf` plugin config?

**Comment by andrewparmet** [comment]
The plugin now supports a `generate {}` configuration in the extension. Try it out and let me know how it goes.

You will have to create the `buf.lock` file yourself. Maybe one day this plugin can call `buf mod update` on its own, but for projects that don't declare dependencies this creates a noisy empty `buf.lock` file. There's some work to do to detect if any dependencies are declared before auto-calling `buf mod update`.
