### ISSUE TITLE
Buf plugin can't find "check" task

### ISSUE THREAD

**Issue by erawhctim** [andrewparmet/buf-gradle-plugin#75]
When I apply this plugin to a subproject, it fails with this error message: 
> Task with name 'check' not found in project

When I remove the plugin and run the check task manually, it works fine. 

It seems the plugin tries to access the check task before its _available_, somehow? Any idea what I'm missing?

**Comment by andrewparmet** [comment]
Maybe the plugin is being applied before another plugin that creates the check task? That would be the Java plugin, Kotlin plugin, etc.?

Can you share any snippet of your configuration or an MVP that demonstrates the issue?

**Comment by andrewparmet** [comment]
Which Kotlin plugin is that? I vaguely remember using that notation in the past, but these days I think `id 'org.jetbrains.kotlin.jvm'` is the preferred notation. What happens if you use that plugin?

**Comment by erawhctim** [comment]
That's a good question; I'm not sure why we're not using the newer plugin name.
Unfortunately I end up with the same result with the `org.jetbrains.kotlin.jvm` one 😞 

I'll try and throw together a small repro. sample for you today

**Comment by andrewparmet** [comment]
I pushed a new version that should be more resilient to different plugin application ordering. Try out 0.6.3 and let me know how it goes.

**Comment by andrewparmet** [comment]
Fixed by https://github.com/andrewparmet/buf-gradle-plugin/pull/79. Closing since this issue should be fixed. Feel free to re-open if you still run into trouble.
