### ISSUE TITLE
Can't use corp proxy to download buf artifacts

### ISSUE THREAD

**Issue by catostrophe** [andrewparmet/buf-gradle-plugin#84]
This is not configurable:
https://github.com/andrewparmet/buf-gradle-plugin/blob/2e5498d23462bb6a473fce661ba0ddfecd53cd89/src/main/kotlin/com/parmet/buf/gradle/BufSupport.kt#L29

I would like to use corp Nexus or Artifactory instead.

**Comment by andrewparmet** [comment]
Do you know the patternLayout for your repository? Will you need an Ivy repository?

I'm trying to discern what level of customization to expose, so your answers will help me design the right API. It would be easy, for example, to allow a custom URL while maintaining the same layout as  GitHub releases, but that's a contrived pattern that I wouldn't want to force on users who want to use a custom repository.

On the other hand, if there is a way to tag standard Maven artifacts with the appropriate architecture and have that resolution work automatically, I would want to expose an API similar to how the protobuf-gradle-plugin allows you to specify the `protoc` dependency.

**Comment by catostrophe** [comment]
I think there should be an option NOT to implicitly inject an ivy repo into the project. (This is prohibited in my case).

Instead I should be able to add a corp proxy repo in the build, e.g. in `dependencyResolutionManagement` section.

**Comment by andrewparmet** [comment]
Ok. Does the artifact that the plugin adds - namely, `"bufbuild:buf:${getExtension().toolVersion}:$osPart@$archPart"` (e.g. `bufbuild:buf:1.5.0:Linux@x86_64`) match the artifact that your repository will provide?

**Comment by andrewparmet** [comment]
See also https://github.com/bufbuild/buf/issues/154

**Comment by andrewparmet** [comment]
`buf-gradle-plugin` no longer relies on an Ivy repository as I have published the Buf binaries to Maven Central. Published in version 0.8.1. Give it a try!
