### ISSUE TITLE
Stale version in Gradle Plugin Registry

### ISSUE THREAD

**Issue by remoun** [andrewparmet/buf-gradle-plugin#96]
https://plugins.gradle.org/plugin/com.parmet.buf shows 0.6.3 while GH shows 0.7.1

**Comment by remoun** [comment]
FWIW https://jitpack.io/#andrewparmet/buf-gradle-plugin reports build errors

**Comment by andrewparmet** [comment]
JitPack doesn't have the credentials it needs to sign the artifacts.

I'm having trouble publishing to Sonatype - I've put in a request to be migrated to the new (and hopefully more stable) shared. I can't see how any of the changes to the publishing config could have led to the failures I'm seeing.

**Comment by andrewparmet** [comment]
After much futzing publishing is working again.

https://search.maven.org/artifact/com.parmet/buf-gradle-plugin/0.7.2/jar
https://plugins.gradle.org/plugin/com.parmet.buf/0.7.2 (coming soon)

**Comment by remoun** [comment]
https://plugins.gradle.org/plugin/com.parmet.buf still reports 0.6.3 as latest

**Comment by andrewparmet** [comment]
0.7.3 published but waiting on approval from the Gradle team since the plugin ID changed by mistake.

**Comment by andrewparmet** [comment]
Ok, 0.8.2 is working. https://plugins.gradle.org/plugin/com.parmet.buf/0.8.2
